module Nghttp3
  class Callbacks
    def initialize: () -> void

    # Stream data callbacks
    def on_acked_stream_data: () { (Integer stream_id, Integer datalen) -> void } -> self
    def on_stream_close: () { (Integer stream_id, Integer app_error_code) -> void } -> self
    def on_recv_data: () { (Integer stream_id, String data) -> void } -> self
    def on_deferred_consume: () { (Integer stream_id, Integer consumed) -> void } -> self

    # Header callbacks
    def on_begin_headers: () { (Integer stream_id) -> void } -> self
    def on_recv_header: () { (Integer stream_id, String name, String value, Integer flags) -> void } -> self
    def on_end_headers: () { (Integer stream_id, bool fin) -> void } -> self

    # Trailer callbacks
    def on_begin_trailers: () { (Integer stream_id) -> void } -> self
    def on_recv_trailer: () { (Integer stream_id, String name, String value, Integer flags) -> void } -> self
    def on_end_trailers: () { (Integer stream_id, bool fin) -> void } -> self

    # Stream control callbacks
    def on_stop_sending: () { (Integer stream_id, Integer app_error_code) -> void } -> self
    def on_end_stream: () { (Integer stream_id) -> void } -> self
    def on_reset_stream: () { (Integer stream_id, Integer app_error_code) -> void } -> self

    # Connection callbacks
    def on_shutdown: () { (Integer id) -> void } -> self
    def on_recv_settings: () { (Hash[Symbol, untyped] settings) -> void } -> self
  end
end
