module Nghttp3
  class Error < StandardError
  end

  class InvalidArgumentError < Error
  end

  class InvalidStateError < Error
  end

  class WouldBlockError < Error
  end

  class StreamInUseError < Error
  end

  class MalformedHTTPHeaderError < Error
  end

  class MalformedHTTPMessagingError < Error
  end

  class QPACKFatalError < Error
  end

  class QPACKHeaderTooLargeError < Error
  end

  class StreamNotFoundError < Error
  end

  class ConnClosingError < Error
  end

  class StreamDataOverflowError < Error
  end

  class FatalError < Error
  end

  class NoMemError < Error
  end

  class CallbackFailureError < Error
  end
end
