module Nghttp3
  class Headers
    include Enumerable[Array[String]]

    def initialize: (?Hash[String | Symbol, String] hash) -> void

    def []: (String | Symbol name) -> String?
    def []=: (String | Symbol name, String | _ToS value) -> String

    def delete: (String | Symbol name) -> String?
    def key?: (String | Symbol name) -> bool
    alias has_key? key?
    alias include? key?

    def each: () { (String name, String value) -> void } -> void
            | () -> Enumerator[Array[String], void]

    def merge!: (Hash[String | Symbol, String] | Headers other) -> self
    def merge: (Hash[String | Symbol, String] | Headers other) -> Headers

    def to_h: () -> Hash[String, String]
    alias to_hash to_h

    def size: () -> Integer
    alias length size

    def empty?: () -> bool
    def clear: () -> self
    def dup: () -> Headers

    def inspect: () -> String

    private

    def normalize_name: (String | Symbol name) -> String
  end
end
